#=====================================================#
#================= Configuration v2 ==================#
#=====================================================#

#=================== Global configuration ============#
url=https://www.onliner.by
capabilities.browserName=chrome
driver_type=local
selenium_url=http://localhost:4444/wd/hub